import { Product, Recipe, JournalPost, Testimonial } from '@/types';

export const productsData: Product[] = [
  {
    id: 'tirma-ceremonial-matcha-ujikyo',
    slug: 'imperial-ceremonial-matcha',
    title: 'Imperial Ceremonial First Flush Matcha',
    subtitle: 'Stone-Milled Uji Tencha • Spring Harvest 2026',
    botanicalName: 'Camellia sinensis var. sinensis',
    category: 'Matcha',
    price: 2450,
    originalPrice: 2800,
    rating: 4.96,
    reviewCount: 142,
    mainImage: '/images/products/matcha.jpg',
    extraPhotos: [
      '/images/products/matcha2.webp',
      '/images/products/matcha3.jpg',
      '/images/products/matcha5.jpg',
    ],
    description: 'A sovereign ceremonial matcha stone-milled in complete darkness from shaded young tencha leaves. Pours a luminous electric jade liquor with profound sweet umami, roasted chestnut nuances, and a thick, cloud-like foam.',
    story: 'Shaded under traditional woven straw reed mats for 28 days prior to the spring solstice. This quiet deprivation of sunlight compels the tea bush to draw concentrated chlorophyll and natural L-theanine into its softest tip leaves.',
    packageSizes: ['30g Hand-Stamped Tin', '80g Washi Paper Pouch', '150g Master Ceramic Tin'],
    origin: 'Uji Highlands, Kyoto Prefecture',
    elevation: '420m Mountain Valley',
    harvest: 'Early Spring First Flush (Ichibancha)',
    pluckingStandard: 'Single tender terminal bud & first leaf',
    liquorColor: 'Luminous Deep Jade',
    flavorNotes: ['Sweet Umami', 'Young Bamboo Shoot', 'Roasted Chestnuts', 'Melted White Chocolate'],
    palateDescription: 'Thick, creamy, velvet mouthfeel with zero astringency and a lingering floral sweetness that hums on the palate for minutes.',
    caffeineLevel: 'High',
    brewingGuide: {
      temp: '75°C - 80°C (167°F - 175°F)',
      ratio: '2g (1 chashaku scoop) per 70ml spring water',
      steepTime: 'Whisk vigorously in W-motion for 40 seconds until dense micro-foam forms',
      infusions: 1,
      vessel: 'Handcrafted Stoneware Chawan',
    },
    ingredients: ['100% Certified Organic Shade-Grown Green Tea Leaves (Stone-Milled)'],
    benefits: [
      'Encourages sustained calm mental clarity via rich L-theanine content',
      'Whole-leaf powder delivers 137x more EGCG antioxidants than brewed bag tea',
      'Restores internal vitality gently without coffee jitters or midday crash',
    ],
    inStock: true,
    isFeatured: true,
    isPopular: true,
    isBanner: true,
  },
  {
    id: 'tirma-silver-needle-cloud-mist',
    slug: 'himalayan-silver-needle-white-tea',
    title: 'Himalayan Silver Needle White Tea',
    subtitle: 'Sun-Dried Downy Spring Buds • Plucked Before Dawn',
    botanicalName: 'Camellia sinensis f. alba',
    category: 'Herbal & Tisane',
    price: 1650,
    originalPrice: 1950,
    rating: 4.94,
    reviewCount: 98,
    mainImage: '/images/products/tea1.jpg',
    extraPhotos: [
      '/images/products/tea2.jpg',
      '/images/products/tea3.jpg',
    ],
    description: 'Plucked exclusively in the hush of dawn while mist cloaks the slopes. Pristine, silvery unfurled tea buds covered in fine downy trichomes yield an ethereal liqueur infused with mountain honeysuckle, honeydew melon, and white peach nectar.',
    story: 'Grown on untouched glacial slopes where high mountain UV light stimulates dense protective white hairs brimming with soothing plant antioxidants. Naturally sun-withered on elevated bamboo trays under open mountain sky.',
    packageSizes: ['50g Airtight Tin', '100g Washi Paper Pouch', '200g Master Jar'],
    origin: 'Mirik Valley, Eastern Himalayas',
    elevation: '1,850m Mountain Cloudbelt',
    harvest: 'Spring Equinox Dawn Pluck',
    pluckingStandard: 'Pure terminal bud only (Single tip)',
    liquorColor: 'Pale Straw & Morning Sunlight',
    flavorNotes: ['Wild Alpine Honeysuckle', 'Honeydew Melon', 'Morning Dew', 'Raw Pine Honey'],
    palateDescription: 'Delicate, silky, and profoundly hydrating. Opens with fresh floral sweetness and finishes with the cool purity of mountain water.',
    caffeineLevel: 'Low',
    brewingGuide: {
      temp: '82°C (180°F)',
      ratio: '3.5g per 200ml soft mountain spring water',
      steepTime: '4 - 5 minutes in glass or glazed ceramic',
      infusions: 4,
      vessel: 'Glass Teapot or Porcelain Gaiwan',
    },
    ingredients: ['100% Pure Organic Sun-Dried White Tea Buds'],
    benefits: [
      'Minimal processing preserves maximum polyphenols and natural plant enzymes',
      'Unusually gentle on sensitive digestion with cooling botanical energy',
      'Promotes cellular hydration and clean, radiant skin wellness',
    ],
    inStock: true,
    isPopular: true,
  },
  {
    id: 'tirma-jade-sencha-fukamushi',
    slug: 'organic-fukamushi-jade-sencha',
    title: 'Deep-Steamed Jade Sencha',
    subtitle: 'Vibrant Fukamushi Green Tea • Shizuoka Slopes',
    botanicalName: 'Camellia sinensis var. Yabukita',
    category: 'Green Tea',
    price: 1150,
    originalPrice: 1350,
    rating: 4.89,
    reviewCount: 84,
    mainImage: '/images/products/tea2.jpg',
    extraPhotos: [
      '/images/products/tea1.jpg',
      '/images/products/matcha2.webp',
    ],
    description: 'Steamed twice as long as ordinary green teas in the ancient Fukamushi tradition. The leaves break gently into fine jade fragments, yielding an intoxicating, cloudy emerald liquor with intense vegetal sweetness and sea breeze mineral purity.',
    story: 'Nurtured in volcanic soils replenished with composted mountain leaves. Deep steaming breaks the leaf cell walls, releasing rich chlorophyll directly into the water.',
    packageSizes: ['75g Estate Tin', '150g Refill Pouch'],
    origin: 'Shizuoka Highland Valleys',
    elevation: '620m Terraced Slopes',
    harvest: 'First Flush Early May',
    pluckingStandard: 'Top two tender leaves and shoot',
    liquorColor: 'Cloudy Vibrant Emerald',
    flavorNotes: ['Steamed Sweet Edamame', 'Sea Grass', 'Sweet Spring Rain', 'Fresh Pine'],
    palateDescription: 'Full-bodied, brothy, and intensely nourishing with a rich savory-sweet finish that completely coats the mouth.',
    caffeineLevel: 'Medium',
    brewingGuide: {
      temp: '70°C - 75°C (158°F - 167°F)',
      ratio: '4g per 200ml spring water',
      steepTime: '50 - 60 seconds (Quick extraction)',
      infusions: 3,
      vessel: 'Kyusu Clay Teapot with Fine Mesh',
    },
    ingredients: ['100% Certified Organic Deep-Steamed Green Tea Leaves'],
    benefits: [
      'Naturally rich in chlorophyll for daily body freshness and renewal',
      'Promotes peaceful concentration during long creative reading and work',
      'Delivers cooling digestive comfort after light midday meals',
    ],
    inStock: true,
    isPopular: true,
  },
  {
    id: 'tirma-golden-darjeeling-first-flush',
    slug: 'royal-darjeeling-first-flush',
    title: 'Royal Darjeeling First Flush',
    subtitle: 'The Champagne of Black Teas • High-Elevation Muscatel',
    botanicalName: 'Camellia sinensis var. sinensis',
    category: 'Black Tea',
    price: 1450,
    originalPrice: 1700,
    rating: 4.95,
    reviewCount: 116,
    mainImage: '/images/products/tea3.jpg',
    extraPhotos: [
      '/images/products/tea4.jpg',
      '/images/products/tea1.jpg',
    ],
    description: 'The celebrated jewel of the Eastern Himalayas. Plucked during the first warming days of spring, the crisp mountain air imparts radiant amber liquor shimmering with notes of ripe muscat grapes, wild forest honey, and crushed peach blossom.',
    story: 'Centenarian tea bushes rooted deep into sub-Himalayan slate terraces. Wilted slowly on raised wooden pavilions as cool alpine breezes pass through.',
    packageSizes: ['60g Heritage Tin', '120g Craft Washi Bag'],
    origin: 'Kurseong Valley, Darjeeling',
    elevation: '1,700m High Ridge',
    harvest: 'Spring Solstice First Flush',
    pluckingStandard: 'Fine two leaves and a silvery bud',
    liquorColor: 'Sparkling Amber Topaz',
    flavorNotes: ['Muscatel Grape', 'Wild Blossom Honey', 'Orchid Petals', 'Crisp Peach'],
    palateDescription: 'Crisp, lively, and elegantly structured with buoyant citrus acidity and a long, golden honeyed aftertaste.',
    caffeineLevel: 'High',
    brewingGuide: {
      temp: '90°C (194°F)',
      ratio: '3g per 200ml pure spring water',
      steepTime: '3 minutes',
      infusions: 3,
      vessel: 'Fine Porcelain or Glass Teapot',
    },
    ingredients: ['100% Certified Organic Whole Leaf Darjeeling Black Tea'],
    benefits: [
      'Provides an uplifting, clean mental awakening without stomach heaviness',
      'Rich in theaflavins and natural plant flavonoids that support heart health',
      'A joyful afternoon ritual that clears mental fatigue effortlessly',
    ],
    inStock: true,
    isPopular: true,
  },
  {
    id: 'tirma-kashmiri-saffron-kahwa',
    slug: 'kashmiri-saffron-kahwa-herbal-blend',
    title: 'Kashmiri Saffron Kahwa Botanical Blend',
    subtitle: 'Green Tea Leaves • Pure Mongra Saffron • Rose & Cardamom',
    botanicalName: 'Camellia sinensis & Crocus sativus',
    category: 'Herbal & Tisane',
    price: 1250,
    originalPrice: 1450,
    rating: 4.98,
    reviewCount: 89,
    mainImage: '/images/products/tea4.jpg',
    extraPhotos: [
      '/images/products/tea2.jpg',
      '/images/products/tea3.jpg',
    ],
    description: 'An ancient regal Himalayan elixir. Organic green tea hand-blended with certified Kashmiri Mongra saffron threads, cracked green cardamom pods, crushed cinnamon bark, and dried organic damask rose petals.',
    story: 'Inspired by centuries of mountain hospitality. Warmed over hearth kettles, this fragrant brew brings instant warmth to cool mornings and soothes the mind after sunset.',
    packageSizes: ['75g Artisanal Tin', '150g Heritage Bag'],
    origin: 'Pampore Highlands & Kangra Valley',
    elevation: '1,600m Himalayan Foothills',
    harvest: 'Autumn Saffron & Spring Green Harvest',
    pluckingStandard: 'Hand-blended whole spices and tender green tea',
    liquorColor: 'Golden Saffron Sun',
    flavorNotes: ['Warm Green Cardamom', 'Honeyed Saffron', 'Damask Rosewater', 'Sweet Cinnamon'],
    palateDescription: 'Aromatic, warm, and comforting. Complex spice notes fold gently into sweet herbal green tea with a rich floral bouquet.',
    caffeineLevel: 'Medium',
    brewingGuide: {
      temp: '88°C - 92°C (190°F - 198°F)',
      ratio: '3.5g per 220ml water (simmer gently or steep covered)',
      steepTime: '4 - 5 minutes',
      infusions: 2,
      vessel: 'Traditional Brass Samovar or Glass Pot',
    },
    ingredients: [
      'Organic Himalayan Green Tea',
      'Whole Pure Kashmiri Mongra Saffron Strands',
      'Green Cardamom Pods',
      'Damask Rose Petals',
      'Ceylon Cinnamon Bark',
    ],
    benefits: [
      'Warming digestive comfort and inner abdominal heat',
      'Saffron’s active safranal naturally uplifts mood and dispels stress',
      'Subtle natural sweetness requires no refined sugar',
    ],
    inStock: true,
    isPopular: true,
  },
  {
    id: 'tirma-chamomile-lavender-calm',
    slug: 'restorative-botanical-calm-tisane',
    title: 'Himalayan Chamomile & Provence Lavender',
    subtitle: 'Whole Sun-Dried Flower Heads • 100% Caffeine-Free',
    botanicalName: 'Matricaria chamomilla & Lavandula angustifolia',
    category: 'Herbal & Tisane',
    price: 850,
    originalPrice: 1000,
    rating: 4.92,
    reviewCount: 63,
    mainImage: '/images/products/matcha5.jpg',
    extraPhotos: [
      '/images/products/tea1.jpg',
      '/images/products/matcha3.jpg',
    ],
    description: 'A sovereign evening bedtime infusion uniting whole golden chamomile blossoms, hand-stripped Provence lavender buds, organic lemon balm leaves, and cooling spearmint. Gentle, comforting, and deeply relaxing.',
    story: 'Harvested by hand when flowers are at full fragrant bloom. Sun-dried under natural shelter to preserve the delicate aromatic essential oils intact.',
    packageSizes: ['50g Airtight Glass Tin', '100g Craft Refill Bag'],
    origin: 'Sun-Drenched Organic Herbal Terraces',
    elevation: '750m Valley Slopes',
    harvest: 'Summer 2025 Floral Harvest',
    pluckingStandard: 'Whole intact blossom heads',
    liquorColor: 'Luminous Pale Gold',
    flavorNotes: ['Sweet Baked Apple', 'Floral Lavender', 'Fresh Lemon Verbena', 'Warm Straw'],
    palateDescription: 'Velvety, soothing, and completely caffeine-free. Envelops the senses like a warm cashmere blanket.',
    caffeineLevel: 'None',
    brewingGuide: {
      temp: '95°C - 100°C (203°F - 212°F)',
      ratio: '3g (approx 2 tbsp whole flowers) per 250ml freshly boiled water',
      steepTime: '6 - 7 minutes covered to lock in volatile oils',
      infusions: 2,
      vessel: 'Covered Ceramic or Glass Teapot',
    },
    ingredients: [
      '100% Whole Organic Chamomile Flowers',
      'Organic Lavender Buds',
      'Organic Lemon Balm Leaves',
      'Organic Spearmint',
    ],
    benefits: [
      'Naturally promotes deep restorative sleep via apigenin flavonoid calm',
      'Relaxes tight evening tension and soothes the digestive tract',
      'Completely free from caffeine — gentle enough for all ages',
    ],
    inStock: true,
  },
  {
    id: 'tirma-oriental-beauty-oolong',
    slug: 'imperial-oriental-beauty-oolong',
    title: 'Imperial Amber Honey Oolong',
    subtitle: 'Wild Bug-Bitten Honey Muscatel • Hsinchu Mountain Terraces',
    botanicalName: 'Camellia sinensis f. oolong',
    category: 'Oolong Tea',
    price: 1850,
    rating: 4.97,
    reviewCount: 76,
    mainImage: '/images/products/tea4.jpg',
    extraPhotos: [
      '/images/products/tea2.jpg',
      '/images/products/tea3.jpg',
    ],
    description: 'Nature’s most enchanting collaboration. Tiny green tea jassid insects feed lightly on the living leaves, stimulating the tea plant to release natural honey and ripe muscat grape defensive terpenes.',
    story: 'Requires a totally pristine, zero-pesticide mountain ecosystem. Only the tender tip and two leaves are hand-plucked during humid summer mornings.',
    packageSizes: ['50g Luxury Tin', '100g Washi Pouch'],
    origin: 'Hsinchu Mountain Terraces',
    elevation: '800m Cloud Ridges',
    harvest: 'Summer Solstice Harvest',
    pluckingStandard: 'One bud with two unfurled leaves',
    liquorColor: 'Warm Copper Amber',
    flavorNotes: ['Wild Mountain Honey', 'Muscatel Grape', 'Orchid Blossom', 'Ripe Autumn Peach'],
    palateDescription: 'Sensuous, nectar-like, and wonderfully complex. Evolves dramatically across five consecutive steeps.',
    caffeineLevel: 'Medium',
    brewingGuide: {
      temp: '88°C (190°F)',
      ratio: '5g per 180ml gaiwan or clay teapot',
      steepTime: '45 seconds (Gongfu style) or 3 minutes Western style',
      infusions: 6,
      vessel: 'Yixing Clay Pot or Porcelain Gaiwan',
    },
    ingredients: ['100% Pure Biodynamic Amber Oolong Tea Leaves'],
    benefits: [
      'Deeply calming and grounding effect after demanding work days',
      'Stimulates smooth digestive metabolism following hearty meals',
      'Six subsequent steepings provide an extended mindfulness ritual',
    ],
    inStock: true,
    isPopular: true,
  },
  {
    id: 'tirma-bamboo-matcha-ceremonial-set',
    slug: 'artisan-bamboo-matcha-ceremony-set',
    title: 'Artisan Bamboo Matcha Ceremony Set',
    subtitle: '100-Prong Golden Bamboo Chasen, Chawan & Celadon Stand',
    category: 'Accessories',
    price: 3200,
    originalPrice: 3800,
    rating: 4.98,
    reviewCount: 52,
    mainImage: '/images/zestaw.png',
    extraPhotos: [
      '/images/podstawka.png',
      '/images/products/matcha2.webp',
    ],
    description: 'A complete heirloom mindfulness tea kit handcrafted by Takayama artisans. Includes a single-piece carved 100-prong golden bamboo whisk (chasen), curved bamboo scoop (chashaku), handcrafted ceramic chawan bowl, and celadon ceramic whisk stand.',
    story: 'Carved from seasoned mountain bamboo split and curled by hand. The fine tines whip air into stone-ground matcha, creating a micro-crema impossible to duplicate with metal whisks.',
    packageSizes: ['Complete 4-Piece Ceremony Set'],
    origin: 'Takayama Mountain Atelier',
    elevation: 'Artisan Studio',
    harvest: 'Hand-Seasoned Golden Bamboo',
    flavorNotes: ['Authentic Micro-Crema Aeration', 'Heirloom Craftsmanship'],
    caffeineLevel: 'None',
    brewingGuide: {
      temp: 'Rinse with warm water before and after use',
      ratio: 'Rest whisk inverted on ceramic stand to maintain bell shape',
      steepTime: 'Allow to air-dry naturally in open air',
      infusions: 999,
      vessel: 'Handcrafted Ceramic Chawan',
    },
    ingredients: ['100% Natural Golden Mountain Bamboo', 'High-Fire Celadon Stoneware'],
    benefits: [
      'Aerates matcha into velvety micro-foam without damaging delicate green antioxidants',
      'Transforms daily hydration into a mindful, centering ceremony',
      'Natural, biodegradable materials that age gracefully over years',
    ],
    inStock: true,
  },
  {
    id: 'tirma-porcelain-whisk-stand',
    slug: 'ceramic-chasen-whisk-holder',
    title: 'Celadon Ceramic Chasen Whisk Stand',
    subtitle: 'Kiln-Fired Glazed Stoneware • Preserves Whisk Curvature',
    category: 'Accessories',
    price: 750,
    rating: 4.88,
    reviewCount: 41,
    mainImage: '/images/podstawka.png',
    extraPhotos: [
      '/images/zestaw.png',
    ],
    description: 'An indispensable companion for any bamboo matcha whisk. Resting your damp whisk on this hollow celadon ceramic cone maintains the delicate curved tines and ensures even air drying.',
    story: 'Fired at 1,280°C with an authentic botanical celadon glaze inspired by young unfurled tea buds.',
    packageSizes: ['Single Ceramic Stand'],
    origin: 'Traditional Ceramic Studio',
    elevation: 'Artisanal Kiln',
    harvest: 'High-Fire Stoneware',
    flavorNotes: ['Enduring Elegance'],
    caffeineLevel: 'None',
    brewingGuide: {
      temp: 'Hand-wash only with warm water',
      ratio: 'Place damp whisk onto cone immediately post-rinse',
      steepTime: 'Air dry in ventilated space',
      infusions: 999,
      vessel: 'Ceramic Stand',
    },
    ingredients: ['100% High-Fire Stoneware Ceramic'],
    benefits: [
      'Multiplies the lifespan of your bamboo whisk tenfold',
      'Prevents mold by allowing complete airflow through delicate tines',
      'A quiet, understated sculptural presence on your counter',
    ],
    inStock: true,
  }
];

export const recipesData: Recipe[] = [
  {
    id: 'recipe-velvet-ceremonial-matcha-latte',
    slug: 'velvet-ceremonial-matcha-latte',
    title: 'The Morning Bowl: Velvet Whisked Usucha',
    subtitle: 'Silky micro-foam with fresh mountain water & steamed oat milk',
    prepTime: '4 Minutes',
    difficulty: 'Simple',
    servings: 1,
    category: 'Morning Ritual',
    image: '/images/products/matcha2.webp',
    description: 'A quiet, centering morning meditation. Combines stone-ground ceremonial matcha with warmed spring water and velvety micro-frothed oat milk to provide 4-6 hours of calm, unshakeable focus.',
    ingredients: [
      '2.5g (1 bamboo chashaku scoop) TIRMA Imperial Ceremonial Matcha',
      '60ml pure spring water heated to 75°C (167°F)',
      '180ml warm creamy oat or almond milk (approx 65°C)',
      '1 tsp raw organic forest honey or jaggery nectar (optional)',
      'Pinch of ground green cardamom (optional Himalayan twist)'
    ],
    steps: [
      'Warm your ceramic chawan bowl with hot water for 30 seconds, then wipe completely dry with a soft cloth.',
      'Sift the green matcha powder through a fine bamboo or brass mesh to eliminate electrostatic clumping.',
      'Pour 60ml of water heated to 75°C (never use boiling water, which burns the sweet amino acids).',
      'Rest your bamboo whisk gently at the bottom of the bowl, then whisk briskly from the wrist in a rapid "W" motion for 35-40 seconds until dense jade micro-foam carpets the surface.',
      'Pour your warm frothed milk gently down the side of the bowl, allowing the emerald foam to rise to the top.'
    ],
    proTips: [
      'Whisk from the wrist with light speed, rather than stirring from the arm or shoulder.',
      'Use water with low mineral hardness (TDS under 60) so the natural mountain sweetness sings.'
    ],
    pairedTeaId: 'tirma-ceremonial-matcha-ujikyo',
    datePublished: 'Harvest 2026',
  },
  {
    id: 'recipe-cold-brew-jade-sencha',
    slug: 'slow-cold-brew-jade-sencha-citrus',
    title: 'The Silent Steep: 12-Hour Chilled Jade Infusion',
    subtitle: 'Chilled mountain extraction yielding zero tannins and high L-theanine',
    prepTime: '12 Hours (Cold Steep)',
    difficulty: 'Simple',
    servings: 4,
    category: 'Chilled Waters',
    image: '/images/products/tea2.jpg',
    description: 'Cold steeping draws out sweet amino acids while keeping harsh tannins locked within the leaf cell walls. The result is pure, invigorating liquid jade that refreshes on hot afternoons.',
    ingredients: [
      '12g TIRMA Deep-Steamed Jade Sencha whole leaves',
      '1 Liter chilled mountain spring or filtered water',
      '2 thin slices of fresh organic lemon or Meyer citrus',
      '3-4 fresh garden mint sprigs',
      'Hand-carved ice cubes'
    ],
    steps: [
      'Place the whole Jade Sencha leaves loose into the bottom of a glass carafe.',
      'Pour chilled filtered spring water gently over the dry leaves.',
      'Add the citrus slices and fresh mint sprigs, submerging them gently.',
      'Cap the bottle and leave undisturbed in the dark refrigerator for 8 to 12 hours.',
      'Strain the liquor through a fine mesh strainer into chilled glasses over ice.'
    ],
    proTips: [
      'The spent green tea leaves can be cold-steeped a second time for 6 hours with delightful results.',
      'Zero astringency makes this the ideal natural hydrator for deep study or meditation.'
    ],
    pairedTeaId: 'tirma-jade-sencha-fukamushi',
    datePublished: 'Harvest 2026',
  },
  {
    id: 'recipe-restorative-evening-tisane',
    slug: 'golden-calm-bedtime-tisane',
    title: 'The Hearth Rest: Golden Evening Flower Tisane',
    subtitle: 'Whole chamomile, crushed cardamom & raw honey',
    prepTime: '6 Minutes',
    difficulty: 'Gentle',
    servings: 2,
    category: 'Evening Calm',
    image: '/images/products/tea1.jpg',
    description: 'A gentle bedtime ceremony designed to signal to your body that the day is over. Inhaling the chamomile and lavender steam quietens evening chatter and invites sound sleep.',
    ingredients: [
      '6g TIRMA Himalayan Chamomile & Lavender Tisane',
      '450ml fresh water brought to a rolling boil (98°C)',
      '1 green cardamom pod, gently crushed open',
      '1 small slice of fresh ginger root',
      '1 tsp raw wildflower honey'
    ],
    steps: [
      'Place the whole chamomile blossoms, lavender, and bruised cardamom into a glass or ceramic pot.',
      'Pour freshly boiled spring water directly over the botanicals.',
      'Cover with a lid immediately — this traps the volatile soothing aromatic oils from escaping.',
      'Let the flowers drift and unfurl for 6 full minutes.',
      'Strain into porcelain cups, stir in raw honey, and inhale the warm floral steam before taking the first sip.'
    ],
    proTips: [
      'Drink 40 minutes before bed away from bright artificial screens for the deepest restorative sleep.',
      'The apigenin flavonoids in whole chamomile bind gently to GABA receptors in the nervous system.'
    ],
    pairedTeaId: 'tirma-chamomile-lavender-calm',
    datePublished: 'Harvest 2026',
  }
];

export const journalPostsData: JournalPost[] = [
  {
    id: 'post-mountain-mist-terroir',
    slug: 'the-mountain-mist-and-living-soil',
    chapter: 'Chapter I',
    title: 'The Mountain Cloud Mist & Living Soil: Why Altitude Changes Everything',
    excerpt: 'Above the 1,500-meter cloud line, tea bushes grow in perpetual conversation with mist, cold nights, and ancient soil loam. Here is what happens inside the leaf.',
    category: 'Terroir & Nature',
    readTime: '5 Min Reflection',
    publishDate: 'September 2026',
    author: {
      name: 'Devan Sharma',
      role: 'Estate Botanist & Tea Master',
      avatar: '/images/products/tea3.jpg',
    },
    image: '/images/products/tea2.jpg',
    tags: ['Terroir', 'Mountain Mist', 'Organic Soil', 'Himalayas'],
    content: {
      introduction: 'When you stand upon a high mountain tea terrace at six in the morning, the silence is almost physical. Clouds roll through the rows like white rivers, wetting your eyelashes and dusting the tender green shoots with micro-droplets of pure mountain moisture.',
      sections: [
        {
          heading: 'Cold Mountain Nights and Sweet Slow Growth',
          body: 'At high altitudes, temperatures drop sharply as soon as the sun dips behind the ridge. This cold shocks the tea plant into slowing its metabolic growth. While commercial low-elevation tea bushes surge rapidly with coarse, water-heavy leaves, high-altitude bushes grow slowly over weeks. In this prolonged stillness, the plant packs dense amino acids, natural sugars, and aromatic terpenes into every millimeter of the tender spring bud.',
        },
        {
          heading: 'The Forest Loam: Feeding Life with Life',
          body: 'Our mountain terraces never encounter a drop of chemical fertilizer. Instead, the soil is enriched with decaying leaves from the surrounding oak and rhododendron forests, composted tea prunings, and natural mountain spring water. A handful of this earth smells dark, rich, and sweet — alive with billions of beneficial mycorrhizal mycelia that trade trace minerals with the tea roots.',
          quote: '“You cannot manufacture flavor in a factory. Flavor is the quiet signature of the earth, written in rainfall, rock dust, and mountain mist.”'
        }
      ],
      conclusion: 'When you steep a cup of high-mountain whole leaf, you are not merely drinking tea. You are tasting the cold night air, the mineral springs, and the patient slowness of an unhurried natural world.'
    }
  },
  {
    id: 'post-anatomy-of-a-shaded-leaf',
    slug: 'the-anatomy-of-a-shaded-leaf-l-theanine',
    chapter: 'Chapter II',
    title: 'The Anatomy of a Shaded Leaf: The Natural Chemistry of L-Theanine',
    excerpt: 'How twenty-eight days of quiet darkness under bamboo straw coax sweet L-theanine into ceremonial matcha, giving you four hours of tranquil focus.',
    category: 'Botanical Alchemy',
    readTime: '6 Min Reflection',
    publishDate: 'September 2026',
    author: {
      name: 'Dr. Meera Sen, PhD',
      role: 'Phytochemist & Herbalist',
      avatar: '/images/products/matcha3.jpg',
    },
    image: '/images/products/matcha.jpg',
    tags: ['L-Theanine', 'Ceremonial Matcha', 'Mindfulness', 'Alchemy'],
    content: {
      introduction: 'For more than eight hundred years, monks in mountain Zen monasteries drank whisked green tea before entering day-long meditation. They knew that while coffee agitated the nervous system, shade-grown tea produced a profound stillness: an alert mind anchored in a relaxed body.',
      sections: [
        {
          heading: 'What Sunlight Does to a Tea Leaf',
          body: 'Under harsh direct sun, a tea plant naturally converts sweet, calming L-theanine into bitter catechins (tannins) to defend its leaves from UV radiation. By constructing raised wooden trestles and covering the tea bushes with traditional reed mats for four weeks before plucking, our cultivators block 90% of direct light.',
        },
        {
          heading: 'The Rise of Pure Chlorophyll and Deep Umami',
          body: 'In the dim, fragrant shade, the plant starves for light and responds by flooding its youngest shoots with intense dark green chlorophyll and precious amino acids. The leaf becomes paper-thin, tender, and saturated with natural umami.',
          quote: '“L-theanine crosses into the brain within thirty minutes, stimulating gentle alpha waves — the same electrical frequency observed during deep creative absorption and peaceful meditation.”'
        }
      ],
      conclusion: 'Every bowl of stone-ground ceremonial matcha is an antidote to modern sensory overload: an ancient, unadulterated plant harmony that restores balance to the mind.'
    }
  },
  {
    id: 'post-the-silent-steep',
    slug: 'the-silent-steep-mindful-brewing',
    chapter: 'Chapter III',
    title: 'The Silent Steep: How Water Temperature Unlocks the Soul of Tea',
    excerpt: 'Why boiling water burns delicate green leaves, and how soft warm water coaxes honeyed nectar instead of harsh bitterness.',
    category: 'The Tea Ceremony',
    readTime: '4 Min Reflection',
    publishDate: 'September 2026',
    author: {
      name: 'Devan Sharma',
      role: 'Estate Botanist & Tea Master',
      avatar: '/images/products/tea3.jpg',
    },
    image: '/images/products/tea4.jpg',
    tags: ['Brewing Ritual', 'Ceremony', 'Water Chemistry', 'Mindfulness'],
    content: {
      introduction: 'Many people believe they dislike green tea because the green tea they have tasted was bitter, biting, and dry. In almost every case, the fault lay not with the leaf, but with the violence of boiling water.',
      sections: [
        {
          heading: 'The Gentle Warmth of Seventy-Five Degrees',
          body: 'Boiling water (100°C) immediately ruptures the fragile cell walls of tender spring leaves, dumping harsh astringent tannins into the cup. But if you allow boiled water to rest in a cooling pitcher until it cools to 70°C–75°C, something miraculous happens: the bitter catechins remain locked in the leaf, while sweet L-theanine, umami amino acids, and floral aroma compounds dissolve effortlessly into the water.',
        },
        {
          heading: 'The Quiet Rhythm of the Pour',
          body: 'Pour your water gently around the perimeter of the pot rather than crashing it directly onto the leaves. Watch the dry, twisted needles slowly drink the warmth, swell, and unfurl like living green ferns rising from sleep.',
          quote: '“Water is the mother of tea; the teapot is its father; and patient attention is its soul.”'
        }
      ],
      conclusion: 'Take five minutes today. Set your phone in another room. Listen to the kettle. Smell the damp warm leaf. Sip in quiet.'
    }
  }
];

export const testimonialsData: Testimonial[] = [
  {
    id: '1',
    name: 'Ananya Raghavan',
    role: 'Ayurvedic Practitioner & Author',
    location: 'Bengaluru, India',
    quote: 'TIRMA’s Imperial Ceremonial Matcha has the sweetest, most unadulterated finish I have ever experienced. You can taste the purity of high-mountain soil and unhurried stone milling in every sip.',
    rating: 5,
    productMentioned: 'Imperial Ceremonial First Flush Matcha',
    avatar: '/images/products/matcha.jpg',
  },
  {
    id: '2',
    name: 'Karan Mehra',
    role: 'Restaurateur & Tea Sommelier',
    location: 'Mumbai, India',
    quote: 'The Himalayan Silver Needle is a revelation. Pale straw liquor with the fragrance of wild honeysuckle and mountain rain. It has transformed my morning reading ritual.',
    rating: 5,
    productMentioned: 'Himalayan Silver Needle White Tea',
    avatar: '/images/products/tea1.jpg',
  },
  {
    id: '3',
    name: 'Pooja Kashyap',
    role: 'Holistic Botanist',
    location: 'New Delhi, India',
    quote: 'The Kashmiri Saffron Kahwa is exquisite — you can see the intact whole saffron threads and green cardamom pods. Truly authentic whole-botanical craftsmanship.',
    rating: 5,
    productMentioned: 'Kashmiri Saffron Kahwa Botanical Blend',
    avatar: '/images/products/tea4.jpg',
  }
];

export const estatePillars = [
  {
    number: '01',
    name: 'The Living Mountain Soil',
    subtitle: 'Free from synthetic fertilizers',
    story: 'Our high-elevation gardens are nourished exclusively with wild forest leaf mold, mountain mulch, and pure spring water, preserving the deep mycorrhizal fungi networks that feed complex sweetness to the roots.',
  },
  {
    number: '02',
    name: 'The Dawn Cloud Pluck',
    subtitle: 'Two tender leaves and a bud',
    story: 'We harvest exclusively by hand in the quiet morning hours while mist clings to the slopes. Only the youngest terminal bud and two leaves are selected, when plant vitality and natural sweetness are at their zenith.',
  },
  {
    number: '03',
    name: 'Natural Solar Withering',
    subtitle: 'Unhurried slow curing',
    story: 'No artificial speed-drying tunnels. The harvested leaves rest upon raised bamboo mats, gently breathing in the cool alpine air and mild mountain sun until their fragrance blossoms naturally.',
  },
  {
    number: '04',
    name: 'Zero-Plastic Whole Botanicals',
    subtitle: 'Pure whole leaf & flower heads',
    story: 'We never grind cheap dust into plastic bags. Every tin contains whole, unbroken leaves or intact flower heads packed in 100% recyclable, airtight hand-stamped tins with zero microplastics.',
  }
];
